version: 0.0
os: linux
files:
  - source: /dist/orderapp
    destination: /var/www/html/dist
 # - source: /scripts/configure_http_port.xsl
 #   destination: //tmp/codedeploy-deployment-staging-area/
hooks:
#  ApplicationStop:
 #   - location: scripts/stop_applicationn
  #    timeout: 300
  BeforeInstall:
    - location: script/cleanup.sh
  #    timeout: 300
  #ApplicationStart:
   # - location: scripts/write_codedeploy_config.sh
  #  - location: scripts/start_application
  #    timeout: 300
 # ValidateService:
  #  - location: scripts/basic_health_check.sh

